services:
  frontend:
    build:
      context: .
      args:
        - PUBLIC_API_URL=${API_URL:-https://carrizales.dev}
    ports:
      - "4300:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4400:4400"
    environment:
      - PORT=4400
    volumes:
      - ./backend/data:/app/data
