services:
  frontend:
    build: .
    ports:
      - "4300:4300"
    environment:
      - PUBLIC_API_URL=https://carrizales.dev
    depends_on:
      - backend
    volumes:
      - ./src:/app/src
      - ./public:/app/public

  backend:
    build: ./backend
    ports:
      - "4400:4400"
    environment:
      - PORT=4400
    volumes:
      - ./backend/data:/app/data
